# Generated by Django 4.0.dev20210331064157 on 2021-04-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_credentials',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('user_type', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=100)),
            ],
        ),
    ]
