# Generated by Django 4.0.dev20210331064157 on 2021-04-25 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_order_book_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bookID',
            new_name='book',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.customer'),
            preserve_default=False,
        ),
    ]
